const pthPrefix = ``;
type Project = {
    title: string;
    dateCreated: string;
    description?: string;
    image: string;
    link: string;
    repository?: string;
    alt: string;
    tags?: string[];
};
export const projectData: Project[] = [
    {
        title: "EvoGym",
        dateCreated: "January 26, 2024",
        description: "Evogym is a fitness app that represents a gym's website. It showcases the gym's services and classes, and also has a fully functioning contact form. The app is built with React, Typescript, and Tailwind CSS. This app is hosted on Heroku.",
        link: "https://evogym-typescript-1g9.pages.dev/",
        repository: "https://github.com/Kennethrc2401/evogym-typescript/tree/main",
        image: `${pthPrefix}EvogymTS.png`,
        alt: "Evogym App",
        tags: ["React", "Typescript", "Tailwind CSS", "Heroku"],
    },
    {
        title: "Threads App Clone (MERN)",
        dateCreated: "August 7, 2023",
        description: "Threads clone is a social media app that allows users to post threads and create communities. It is built with the MERN stack and uses Clerk for authentication. The app is built with Next JS, Typescript, and Tailwind CSS. This app is hosted on Vercel.",
        link: "https://threads-app-clone-rouge.vercel.app/",
        repository: "https://github.com/Kennethrc2401/Threads-App-Clone/tree/main",
        image: `${pthPrefix}Threads_App_Clone.png`,
        alt: "Ecomvision Admin Dashboard",
        tags: ["Next JS", "Typescript", "Tailwind CSS", "Vercel", "Clerk", "Full Stack", "MongoDB", "Express", "React", "Node JS"],
    },
    {   
        title: "React Native Jobs",
        dateCreated: "March 23, 2023",
        description: "...",
        image: `${pthPrefix}React_Native_Jobs_v1.png`,
        link: "https://github.com/Kennethrc2401/react_native_jobs",
        repository: "https://github.com/Kennethrc2401/react_native_jobs/tree/master",
        alt: "React Native Jobs App",
        tags: ["React Native", "Expo", "Axios", "Full Stack", "React", "Node JS", "JavaScript", "API"],
    },
    {
        title: "Ecomvision Admin Dashboard (MERN)",
        dateCreated: "February 26, 2023",
        description: "Ecomvision Admin Dashboard is a full-stack MERN app that allows users to manage products, orders, and users. The app is built with React and Redux for the front-end, and Node JS, Express, and MongoDB for the back-end.",
        image: `${pthPrefix}EcomvisionAdminDashboardMERN.png`,        
        link: "https://github.com/Kennethrc2401/EcomvisionAdminDashboardMERN-Server",
        repository: "https://github.com/Kennethrc2401/StudentLocatorv3_Server",
        alt: "EcomvisionAdminDashboardMERN",
        tags: ["React", "Redux", "Node JS", "Express", "MongoDB", "Full Stack", "MERN"],
    },
    {
        title: "React TypeScript Shopping Cart",
        dateCreated: "February 14, 2023",
        description: "A simple shopping cart app built with React and Typescript. The app uses Tailwind CSS for styling and is hosted on Render.",
        image: `${pthPrefix}ReactTsShoppingCart.png`,
        link: "https://react-ts-shopping-cart-jwiy.onrender.com/",
        repository: "https://github.com/Kennethrc2401/react-ts-shopping-cart",
        alt: "React Ts Shopping Cart",
        tags: ["React", "Typescript", "Tailwind CSS", "Render"],
    },
    {
        title: "Tech Notes (MERN)",
        dateCreated: "February 2, 2023",
        description: "Tech Notes is a full-stack MERN app that allows users to create, read, update, and delete tech notes. The app is built with React for the front-end, and Node JS, Express, and MongoDB for the back-end.",
        image: `${pthPrefix}TechNotes.png`,
        link: "https://github.com/Kennethrc2401/mern-stack-project1",
        repository: "https://github.com/Kennethrc2401/mern-stack-project1",
        alt: "Tech Notes",
        tags: ["React", "Node JS", "Express", "MongoDB", "Full Stack", "MERN"],
    },
    {
        title: "To Do App (IBM Week 5)",
        dateCreated: "January 31, 2023",
        description: "To Do List App is a simple app that allows users to create, read, update, and delete to-do items. The app is built with JavaScript, HTML, and CSS, and uses Axios for API calls and Material UI for styling.",
        image: `${pthPrefix}IBM_ToDoListAppW5.png`,
        link: "https://github.com/Kennethrc2401/toDoList-IBM-W5",
        repository: "https://github.com/Kennethrc2401/toDoList-IBM-W5",
        alt: "To Do List App IBM Week 5 project",
        tags: ["JavaScript", "HTML", "CSS", "Axios", "Material UI"],
    },
    {
        title: "Kenneth's Portfolio 2023v2",
        dateCreated: "December 1, 2022",
        description: "This is the second version of my portfolio. It is built with React.",
        link: "https://github.com/Kennethrc2401/krc_portfolio2023v2",
        repository: "https://github.com/Kennethrc2401/krc_portfolio2023v2",
        image: `${pthPrefix}KRC_Portfolio2023V2.png`,
        alt: "Kenneths Portfolio 2023v2",
        tags: ["React"],
    },
    {
        title: "Mother's Day 2019",
        description: "A simple Mother's Day card.",
        dateCreated: "May 11, 2019",
        link: "https://kennethrc2401.github.io/Mother-s-Day-2019/",
        image: `${pthPrefix}mothers_day_2019.png`,
        alt: "Mothers Day 2019",
        tags: ["HTML", "CSS"],
    },
    {
        title: "Happy Easter 2019",
        dateCreated: "April 20, 2019",
        description: "...",
        link: "https://kennethrc2401.github.io/Happy-Easter-2019/",
        image: `${pthPrefix}HappyEaster2019.png`,
        alt: "Happy Easter 2019",
    },
    {
        title: "JS Issue Tracker",
        dateCreated: "April 18, 2019",
        description: "...",
        link: "https://kennethrc2401.github.io/JS-Issue-Tracker/#",
        image: `${pthPrefix}JS-Issue-Tracker.png`,
        alt: "JS Issue Tracker",
    },
    {
        title: "Spanish Honor Society - HHS",
        dateCreated: "March 12, 2019",
        description: "...",
        link: "https://kennethrc2401.github.io/Spanish-Honor-Society/",
        image: `${pthPrefix}spanish_honor_society_hhs.png`,
        alt: "Spanish Honor Society",
    },
    {
        title: "Happy Holidays 2018-2019!",
        dateCreated: "November 29, 2018",
        description: "...",
        link: "https://kennethrc2401.github.io/Happy-Holidays-2018-2019/",
        image: `${pthPrefix}HappyHolidays201819.png`,
        alt: "Happy Holidays 2018-2019",
    },
    {
        title: "Happy Thanksgiving 2018!",
        dateCreated: "November 19, 2018",
        description: "...",
        link: "https://kennethrc2401.github.io/Thanksgiving-2018/",
        image: `${pthPrefix}HappyThanksgiving2018.png`,
        alt: "Happy Thanksgiving 2018",
    },
    {
        title: "Happy Halloween 2018!",
        dateCreated: "October 26, 2018",
        description: "...",
        link: "https://kennethrc2401.github.io/HappyHalloween2018/",
        image: `${pthPrefix}HappyHalloween2018.png`,
        alt: "Happy Halloween 2018",
    },
    {
        title: "My Times",
        dateCreated: "May 06, 2018",
        description: "...",
        link: "https://kennethrc2401.github.io/MyTimes/",
        image: `${pthPrefix}MyTimes.png`,
        alt: "My Times",
    },
    {
        title: "Dasmoto's Arts Crafts",
        dateCreated: "May 06, 2018",
        description: "...",
        link: "https://kennethrc2401.github.io/Dasmoto-s_Arts_-_Crafts/",
        image: `${pthPrefix}Dasmoto.png`,
        alt: "Dasmoto's Arts Crafts",
    },
    {
        title: "Kenneth's Portfolio",
        dateCreated: "April 12, 2018",
        description: "...",
        link: "https://kennethrc2401.github.io/Kenneth-s_Portfolio/",
        image: `${pthPrefix}Kenneth-s_Portfolio.png`,
        alt: "Kenneth's Portfolio",
    },
    {
        title: "WareHouse - Capstone Project",
        dateCreated: "February 21, 2018",
        description: "...",
        link: "https://kennethrc2401.github.io/Warehouse-Capstone-Project/",
        image: `${pthPrefix}WareHouse.png`,
        alt: "WareHouse - Capstone Project",
    },
    {
        title: "Hotels in Singapore",
        dateCreated: "February 19, 2018",
        description: "Implementing site Breadcrumb navigation.",
        link: "https://kennethrc2401.github.io/Hotels_In_Singapore-Navigation/",
        image: `${pthPrefix}Hotels-In-Singapore.png`,
        alt: "Hotels in Singapore",
    },
    {
        title: "Typography - Assignment",
        dateCreated: "February 18, 2018",
        description: "Assignment for the Codecademy Build Website UIs Pro Intensive course.",
        link: "https://kennethrc2401.github.io/typography-for-ui-cumulative-starting-point/",
        image: `${pthPrefix}Typography.png`,
        alt: "Typography - Assignment",
    },
    {
        title: "ReactJS Sample Project",
        dateCreated: "February 13, 2018",
        description: "...",
        link: "https://kennethrc2401.github.io/ReactJs-Project/",
        image: `${pthPrefix}ReactJS-Project.png`,
        alt: "ReactJS Sample Project",
    },
    {
        title: "Valentines Day 2018",
        dateCreated: "February 12, 2018",
        description: "...",
        link: "https://kennethrc2401.github.io/Valentines-Day-2018/",
        image: `${pthPrefix}Valentines-Day2018.png`,
        alt: "Valentines Day 2018",
    },
    {
        title: "ticketCITY",
        dateCreated: "February 01, 2018",
        description: "...",
        link: "https://kennethrc2401.github.io/ticketCITY/",
        image: `${pthPrefix}TicketCity.png`,
        alt: "ticketCITY",
    },
    {
        title: "Jumpstart",
        dateCreated: "January 09, 2018",
        description: "...",
        link: "https://kennethrc2401.github.io/Jumpstart_v2/#",
        image: `${pthPrefix}Jumpstart.png`,
        alt: "Jumpstart",
    },
    {
        title: "Trackster",
        dateCreated: "January 08, 2018",
        description: "...",
        link: "https://kennethrc2401.github.io/Trackster/",
        image: `${pthPrefix}Trackster.png`,
        alt: "Trackster",
    },
    {
        title: "Fresh Deals",
        dateCreated: "December 27, 2017",
        description: "...",
        link: "https://kennethrc2401.github.io/Fresh_Deals/index.html",
        image: `${pthPrefix}Fresh_Deals.png`,
        alt: "Fresh Deals",
    },
    {
        title: "Vacation World",
        dateCreated: "December 26, 2017",
        description: "...",
        link: "https://kennethrc2401.github.io/Vacation_World/",
        image: `${pthPrefix}Vacation-World.png`,
        alt: "Vacation World",
    },
    {
        title: "Quinoa and Kale Salad Recipe",
        dateCreated: "December 26, 2017",
        description: "...",
        link: "https://kennethrc2401.github.io/Quinoa_and_Kale_Salad_Recipe/",
        image: `${pthPrefix}Quinoa_and_Kale_Salad_Recipe.png`,
        alt: "Quinoa and Kale Salad Recipe",
    },
    {
        title: "Match Game",
        dateCreated: "December 22, 2017",
        description: "...",
        link: "https://kennethrc2401.github.io/Match-Game-Codecademy/",
        image: `${pthPrefix}Match-Game.png`,
        alt: "Match Game",
    },
    {
        title: "Colmar Academy - Capstone Project",
        dateCreated: "Dec 12, 2017",
        description: "...",
        link: "https://kennethrc2401.github.io/Colmar-Academy/",
        image: `${pthPrefix}Colmar_Academy.png`,
        alt: "Colmar Academy - Capstone Project",
    },
    {
        title: "Fotomatic",
        dateCreated: "December 09, 2017",
        description: "...",
        link: "https://kennethrc2401.github.io/Fotomatic/",
        image: `${pthPrefix}Fotomatic.png`,
        alt: "Fotomatic",
    },
    {
        title: "Tortoiseshell Optics",
        dateCreated: "December 09, 2017",
        description: "...",
        link: "https://kennethrc2401.github.io/Tortoiseshell_Optics_v2/",
        image: `${pthPrefix}TortoiseShell_Optics.png`,
        alt: "Tortoiseshell Optics",
    },
    {
        title: "Secret Agent Supply",
        dateCreated: "December 07, 2017",
        description: "...",
        link: "https://kennethrc2401.github.io/SecretAgentSupply/",
        image: `${pthPrefix}SecretAgentSupply.png`,
        alt: "Secret Agent Supply",
    },
    {
        title: "Tea Cozy",
        dateCreated: "December 02, 2017",
        description: "...",
        link: "https://kennethrc2401.github.io/Tea_Cozy/",
        image: `${pthPrefix}Tea_Cozy.png`,
        alt: "Tea Cozy",
    },
    {
        title: "Broadway Design",
        dateCreated: "November 27, 2017",
        description: "...",
        link: "https://kennethrc2401.github.io/Broadway/",
        image: `${pthPrefix}Broadway.png`,
        alt: "Broadway Design",
    }
];